version: '3.1'
services:
  task-1:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/home/comparisons/suites
  task-2:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/home/comparisons/suites
